server:
  name: vending
  port: 9069

log:
  logFileDir: ./logs
  appName: vending-New
  errorFileName: err.log
  warnFileName: warn.log
  infoFileName: info.log
  debugFileName: debug.log
  maxSize: 100
  maxBackups: 60
  maxAge: 3
  development: true
  level: -1

redis:
  host: 127.0.0.1:6379
  password:
  poolsize:

mongo:
  host: 139.9.0.61:17017
  user:
  password:
  poolsize: 4096
  maxConnIdleTime: 6000

mysql:
  dbName: test
  host: 127.0.0.1:3306
  user: root
  password: root

jwt:
  jwtSecret: 'scncys'
  jwtExpireTime: 3600
  issuer: 'test.com'
  jwtAuthKey: 'API_TOKEN'