// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"vending/app/adapter/http/handlers/business"
	"vending/app/adapter/http/server"
	"vending/app/application/service/impl"
	"vending/app/domain/service"
	"vending/app/infrastructure/config"
	"vending/app/infrastructure/repository"
	"vending/app/infrastructure/repository/auth"
)

// Injectors from wire.go:

func NewHandler() *server.Handlers {
	userMgoRepository := auth.NewUserRepository()
	repositoryRepository := repository.NewRepository(userMgoRepository)
	serviceService := service.NewService(repositoryRepository)
	authSrvImp := impl.NewAuthSrvImp(serviceService)
	authHandler := business.NewAuthHandler(authSrvImp)
	handlers := server.NewHandlers(authHandler)
	return handlers
}

// wire.go:

var providerSet = wire.NewSet(config.NewConfig, auth.NewUserRepository, repository.NewRepository, service.NewService, impl.NewAuthSrvImp, business.NewAuthHandler, server.NewHandlers)
